In [56]:
import numpy as np
import pandas as pd

In [57]:
import sys
print(sys.executable)

c:\Users\chava\AppData\Local\Programs\Python\Python313\python.exe

In [58]:
array=[1,38,67,5,98]
arr = np.array(array)
print(arr)
hi = np.linspace(1,8,num =4,dtype= int)
print(hi)

[ 1 38 67  5 98]
[1 3 5 8]

In [59]:
print(hi[:2])
new_arr= arr[1:].copy()
new_arr[2]=90
print(arr)
print(new_arr)

[1 3]
[ 1 38 67  5 98]
[38 67 90 98]

In [60]:
arr3D = np.array([[[1,8],[33,55],[6,9]],[[45,7],[89,54],[89,78]]])
print(arr3D)
arr3D_d=arr3D.reshape(6,2)
print(arr3D_d)

[[[ 1  8]
  [33 55]
  [ 6  9]]

 [[45  7]
  [89 54]
  [89 78]]]
[[ 1  8]
 [33 55]
 [ 6  9]
 [45  7]
 [89 54]
 [89 78]]

In [61]:
print(hi ** 2)

[ 1  9 25 64]

In [62]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\chava\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\chava\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [63]:
import openpyxl

In [64]:
df = pd.read_excel(r"C:\Users\chava\Downloads\MOCK_DATA (1).xlsx")
df.sample(5)

,Student Roll no.,first_name,last_name,email,Department,CGPA,Resume link
27,28,Moyna,Raeburn,mraeburnr@hugedomains.com,INFT,8.85,https://oakley.com/lobortis.aspx?sed=feugiat&t...
20,21,Marcela,Croser,mcroserk@edublogs.org,ELEC,9.01,https://nationalgeographic.com/ut/at/dolor/qui...
24,25,Druci,Thrift,dthrifto@mapquest.com,INFT,8.51,https://macromedia.com/sapien/a/libero/nam/dui...
31,32,Godart,Fridlington,gfridlingtonv@indiegogo.com,ELEC,7.53,http://mapy.cz/accumsan/odio/curabitur/convall...
4,5,Uri,Copestake,ucopestake4@dailymail.co.uk,ELEC,9.00,https://cargocollective.com/luctus/tincidunt/n...

In [65]:
# resume_links = df["Resume link"].to_list()
# df.drop(columns=["Resume link"],inplace=True)

In [66]:
df.drop_duplicates(subset=["email","first_name","last_name"])

,Student Roll no.,first_name,last_name,email,Department,CGPA,Resume link
0,1,Gertie,Blaske,gblaske0@imdb.com,ELEC,8.63,http://cdc.gov/erat.png?integer=urna&ac=ut&neq...
1,2,Dall,Edgin,dedgin1@un.org,CMPN,8.67,https://kickstarter.com/mattis/egestas.html?nu...
2,3,Conny,Peppard,cpeppard2@360.cn,ELEC,7.85,https://ning.com/nullam/porttitor/lacus/at/tur...
3,4,Karry,Stille,kstille3@sun.com,ELEC,9.34,http://seattletimes.com/quis.js?urna=at&ut=vel...
4,5,Uri,Copestake,ucopestake4@dailymail.co.uk,ELEC,9.00,https://cargocollective.com/luctus/tincidunt/n...
5,6,Bev,Jerdan,bjerdan5@comsenz.com,ELEC,8.54,http://washington.edu/erat.xml?vitae=lacinia&c...
6,7,Kelly,Fergyson,kfergyson6@bing.com,ECS,8.89,https://google.ca/diam/erat/fermentum/justo.js...
7,8,Josefa,Delion,jdelion7@wix.com,ELEC,8.25,https://berkeley.edu/non/mi/integer/ac/neque/d...
8,9,Avivah,Botger,abotger8@dropbox.com,ECS,8.24,https://webnode.com/enim/leo/rhoncus/sed.jsp?e...
9,10,Pauli,Probyn,pprobyn9@bravesites.com,INFT,8.08,http://infoseek.co.jp/viverra/pede/ac.xml?maec...
10,11,Anna-diana,Joderli,ajoderlia@fda.gov,ELEC,8.42,http://bigcartel.com/mauris/morbi/non/lectus.j...
11,12,Basil,Walters,bwaltersb@shutterfly.com,CMPN,8.24,https://home.pl/felis.jsp?sed=odio&ante=curabi...
12,13,Rania,Halliday,rhallidayc@cargocollective.com,CMPN,7.39,http://theatlantic.com/sapien/a/libero/nam/dui...
13,14,Leonard,Banasik,lbanasikd@google.nl,CMPN,7.92,http://kickstarter.com/sapien.png?ultrices=nec...
14,15,Shelagh,Drayson,sdraysone@ifeng.com,INFT,8.99,https://youtu.be/fusce.png?maecenas=habitasse&...
15,16,Mark,Sharpus,msharpusf@ocn.ne.jp,INFT,8.99,http://theguardian.com/nisi/venenatis/tristiqu...
16,17,Nora,Annies,nanniesg@google.co.uk,ECS,8.46,http://ebay.co.uk/convallis/nunc/proin.xml?vel...
17,18,Druci,Alsobrook,dalsobrookh@engadget.com,ELEC,8.06,https://ifeng.com/odio/curabitur/convallis/dui...
18,19,Leia,McGeachy,lmcgeachyi@redcross.org,ECS,9.81,http://patch.com/eget/nunc/donec.aspx?nunc=tem...
19,20,Gibbie,Rattrie,grattriej@bbc.co.uk,ECS,9.90,http://instagram.com/turpis/donec.jsp?dui=volu...
20,21,Marcela,Croser,mcroserk@edublogs.org,ELEC,9.01,https://nationalgeographic.com/ut/at/dolor/qui...
21,22,Sayres,Germaine,sgermainel@cbc.ca,ELEC,8.50,http://cnbc.com/suspendisse/accumsan.js?faucib...
22,23,Dionne,Rearden,dreardenm@multiply.com,INFT,9.58,http://wikia.com/aliquet/pulvinar/sed/nisl.jso...
23,24,Arny,Vogele,avogelen@themeforest.net,INFT,9.81,http://ifeng.com/convallis.json?etiam=dolor&pr...
24,25,Druci,Thrift,dthrifto@mapquest.com,INFT,8.51,https://macromedia.com/sapien/a/libero/nam/dui...
25,26,Agathe,Francello,afrancellop@goo.ne.jp,INFT,8.08,https://mayoclinic.com/nulla/mollis/molestie/l...
26,27,Maisey,Howling,mhowlingq@abc.net.au,ELEC,8.94,https://digg.com/velit/eu/est/congue.xml?proin...
27,28,Moyna,Raeburn,mraeburnr@hugedomains.com,INFT,8.85,https://oakley.com/lobortis.aspx?sed=feugiat&t...
28,29,Raddie,Jendricke,rjendrickes@amazon.com,ELEC,8.91,http://bbc.co.uk/morbi.js?in=pellentesque&fauc...
29,30,Othilia,Risborough,orisborought@blog.com,ELEC,7.08,https://google.com.br/sit/amet/sapien/dignissi...
30,31,Mela,Exell,mexellu@cbslocal.com,CMPN,8.23,https://topsy.com/duis/faucibus/accumsan/odio/...
31,32,Godart,Fridlington,gfridlingtonv@indiegogo.com,ELEC,7.53,http://mapy.cz/accumsan/odio/curabitur/convall...
32,33,Rosalinda,Leaver,rleaverw@nyu.edu,INFT,8.47,https://state.tx.us/consequat/lectus.aspx?done...
33,34,Leila,Swire,lswirex@simplemachines.org,ECS,7.71,http://un.org/id/luctus/nec.png?nisi=dui&eu=ve...
34,35,Giffy,Nowell,gnowelly@ovh.net,ECS,7.73,https://theglobeandmail.com/duis/bibendum.xml?...
35,36,Paridnya,Jalgoankar,paridnyajalgoankar@atharvacoe.ac.in,ECS,8.50,file:///C:/Users/chava/Downloads/CV_2026082709...

In [67]:
# idx = df.groupby(["first_name","last_name"])["CGPA"].idxmax()
# print(idx)
# cleaned_df = df.loc[idx].sort_values(by="CGPA",ascending=False)

In [68]:
cleaned_df=df[df["CGPA"]>=9.0]
print(cleaned_df)

    Student Roll no. first_name  last_name                        email  \
3                  4      Karry     Stille             kstille3@sun.com
4                  5        Uri  Copestake  ucopestake4@dailymail.co.uk
18                19       Leia   McGeachy      lmcgeachyi@redcross.org
19                20     Gibbie    Rattrie          grattriej@bbc.co.uk
20                21    Marcela     Croser        mcroserk@edublogs.org
22                23     Dionne    Rearden       dreardenm@multiply.com
23                24       Arny     Vogele     avogelen@themeforest.net

   Department  CGPA                                        Resume link
3        ELEC  9.34  http://seattletimes.com/quis.js?urna=at&ut=vel...
4        ELEC  9.00  https://cargocollective.com/luctus/tincidunt/n...
18        ECS  9.81  http://patch.com/eget/nunc/donec.aspx?nunc=tem...
19        ECS  9.90  http://instagram.com/turpis/donec.jsp?dui=volu...
20       ELEC  9.01  https://nationalgeographic.com/ut/at/dolor/qui...
22       INFT  9.58  http://wikia.com/aliquet/pulvinar/sed/nisl.jso...
23       INFT  9.81  http://ifeng.com/convallis.json?etiam=dolor&pr...

In [69]:
df["CGPA"].astype(int)
cleaned_df = df[(df["CGPA"]>=8.5)&((df["Department"]=="CMPN") | (df["Department"]=="INFT"))]
cleaned_df=cleaned_df.sort_values("CGPA",ascending=False)
print(cleaned_df)

    Student Roll no. first_name last_name                      email  \
23                24       Arny    Vogele   avogelen@themeforest.net
22                23     Dionne   Rearden     dreardenm@multiply.com
14                15    Shelagh   Drayson        sdraysone@ifeng.com
15                16       Mark   Sharpus        msharpusf@ocn.ne.jp
27                28      Moyna   Raeburn  mraeburnr@hugedomains.com
1                  2       Dall     Edgin             dedgin1@un.org
24                25      Druci    Thrift      dthrifto@mapquest.com

   Department  CGPA                                        Resume link
23       INFT  9.81  http://ifeng.com/convallis.json?etiam=dolor&pr...
22       INFT  9.58  http://wikia.com/aliquet/pulvinar/sed/nisl.jso...
14       INFT  8.99  https://youtu.be/fusce.png?maecenas=habitasse&...
15       INFT  8.99  http://theguardian.com/nisi/venenatis/tristiqu...
27       INFT  8.85  https://oakley.com/lobortis.aspx?sed=feugiat&t...
1        CMPN  8.67  https://kickstarter.com/mattis/egestas.html?nu...
24       INFT  8.51  https://macromedia.com/sapien/a/libero/nam/dui...

In [70]:
# print(resume_links)
resume_links=df.groupby("first_name")["Resume link"].apply(list)
print(resume_links)

first_name
Agathe        [https://mayoclinic.com/nulla/mollis/molestie/...
Anna-diana    [http://bigcartel.com/mauris/morbi/non/lectus....
Arny          [http://ifeng.com/convallis.json?etiam=dolor&p...
Avivah        [https://webnode.com/enim/leo/rhoncus/sed.jsp?...
Basil         [https://home.pl/felis.jsp?sed=odio&ante=curab...
Bev           [http://washington.edu/erat.xml?vitae=lacinia&...
Conny         [https://ning.com/nullam/porttitor/lacus/at/tu...
Dall          [https://kickstarter.com/mattis/egestas.html?n...
Dionne        [http://wikia.com/aliquet/pulvinar/sed/nisl.js...
Druci         [https://ifeng.com/odio/curabitur/convallis/du...
Gertie        [http://cdc.gov/erat.png?integer=urna&ac=ut&ne...
Gibbie        [http://instagram.com/turpis/donec.jsp?dui=vol...
Giffy         [https://theglobeandmail.com/duis/bibendum.xml...
Godart        [http://mapy.cz/accumsan/odio/curabitur/conval...
Josefa        [https://berkeley.edu/non/mi/integer/ac/neque/...
Karry         [http://seattletimes.com/quis.js?urna=at&ut=ve...
Kelly         [https://google.ca/diam/erat/fermentum/justo.j...
Leia          [http://patch.com/eget/nunc/donec.aspx?nunc=te...
Leila         [http://un.org/id/luctus/nec.png?nisi=dui&eu=v...
Leonard       [http://kickstarter.com/sapien.png?ultrices=ne...
Maisey        [https://digg.com/velit/eu/est/congue.xml?proi...
Marcela       [https://nationalgeographic.com/ut/at/dolor/qu...
Mark          [http://theguardian.com/nisi/venenatis/tristiq...
Mela          [https://topsy.com/duis/faucibus/accumsan/odio...
Moyna         [https://oakley.com/lobortis.aspx?sed=feugiat&...
Nora          [http://ebay.co.uk/convallis/nunc/proin.xml?ve...
Othilia       [https://google.com.br/sit/amet/sapien/digniss...
Paridnya      [file:///C:/Users/chava/Downloads/CV_202608270...
Pauli         [http://infoseek.co.jp/viverra/pede/ac.xml?mae...
Raddie        [http://bbc.co.uk/morbi.js?in=pellentesque&fau...
Rania         [http://theatlantic.com/sapien/a/libero/nam/du...
Rosalinda     [https://state.tx.us/consequat/lectus.aspx?don...
Sayres        [http://cnbc.com/suspendisse/accumsan.js?fauci...
Shelagh       [https://youtu.be/fusce.png?maecenas=habitasse...
Uri           [https://cargocollective.com/luctus/tincidunt/...
Name: Resume link, dtype: object

In [ ]:
from urllib.parse import urlparse
valid_url =[]
for i in resume_links:
    parsed_url = urlparse(i)
    if parsed_url.scheme=="https":
        valid_url.append(i)

['https://mayoclinic.com/nulla/mollis/molestie/lorem/quisque.png?duis=lectus&ac=aliquam&nibh=sit&fusce=amet&lacus=diam&purus=in&aliquet=magna&at=bibendum&feugiat=imperdiet&non=nullam&pretium=orci&quis=pede&lectus=venenatis&suspendisse=non&potenti=sodales&in=sed&eleifend=tincidunt&quam=eu&a=felis&odio=fusce&in=posuere&hac=felis&habitasse=sed&platea=lacus&dictumst=morbi&maecenas=sem&ut=mauris&massa=laoreet&quis=ut&augue=rhoncus']
['http://bigcartel.com/mauris/morbi/non/lectus.jpg?scelerisque=et&mauris=commodo&sit=vulputate&amet=justo&eros=in&suspendisse=blandit&accumsan=ultrices&tortor=enim&quis=lorem&turpis=ipsum&sed=dolor&ante=sit&vivamus=amet&tortor=consectetuer&duis=adipiscing&mattis=elit&egestas=proin&metus=interdum&aenean=mauris&fermentum=non&donec=ligula&ut=pellentesque&mauris=ultrices&eget=phasellus&massa=id&tempor=sapien&convallis=in&nulla=sapien&neque=iaculis&libero=congue&convallis=vivamus&eget=metus&eleifend=arcu&luctus=adipiscing&ultricies=molestie&eu=hendrerit&nibh=at&quisque=vulputate&id=vitae&justo=nisl&sit=aenean&amet=lectus&sapien=pellentesque&dignissim=eget&vestibulum=nunc&vestibulum=donec&ante=quis&ipsum=orci&primis=eget&in=orci&faucibus=vehicula&orci=condimentum&luctus=curabitur&et=in&ultrices=libero&posuere=ut&cubilia=massa&curae=volutpat&nulla=convallis&dapibus=morbi&dolor=odio&vel=odio&est=elementum&donec=eu&odio=interdum&justo=eu&sollicitudin=tincidunt&ut=in&suscipit=leo&a=maecenas&feugiat=pulvinar&et=lobortis&eros=est&vestibulum=phasellus&ac=sit&est=amet&lacinia=erat&nisi=nulla&venenatis=tempus&tristique=vivamus&fusce=in&congue=felis']
['http://ifeng.com/convallis.json?etiam=dolor&pretium=sit&iaculis=amet&justo=consectetuer&in=adipiscing&hac=elit&habitasse=proin&platea=interdum&dictumst=mauris&etiam=non&faucibus=ligula&cursus=pellentesque&urna=ultrices&ut=phasellus&tellus=id&nulla=sapien&ut=in&erat=sapien&id=iaculis&mauris=congue&vulputate=vivamus&elementum=metus&nullam=arcu&varius=adipiscing&nulla=molestie&facilisi=hendrerit&cras=at']
['https://webnode.com/enim/leo/rhoncus/sed.jsp?eu=nunc&est=purus&congue=phasellus&elementum=in&in=felis&hac=donec&habitasse=semper&platea=sapien&dictumst=a&morbi=libero&vestibulum=nam&velit=dui&id=proin&pretium=leo&iaculis=odio&diam=porttitor&erat=id&fermentum=consequat&justo=in&nec=consequat&condimentum=ut&neque=nulla&sapien=sed&placerat=accumsan&ante=felis&nulla=ut&justo=at&aliquam=dolor&quis=quis&turpis=odio&eget=consequat&elit=varius&sodales=integer&scelerisque=ac&mauris=leo&sit=pellentesque&amet=ultrices&eros=mattis&suspendisse=odio&accumsan=donec&tortor=vitae&quis=nisi&turpis=nam&sed=ultrices&ante=libero&vivamus=non&tortor=mattis&duis=pulvinar&mattis=nulla&egestas=pede&metus=ullamcorper&aenean=augue&fermentum=a&donec=suscipit&ut=nulla&mauris=elit&eget=ac&massa=nulla&tempor=sed&convallis=vel&nulla=enim&neque=sit&libero=amet&convallis=nunc&eget=viverra&eleifend=dapibus&luctus=nulla&ultricies=suscipit&eu=ligula&nibh=in']
['https://home.pl/felis.jsp?sed=odio&ante=curabitur&vivamus=convallis&tortor=duis&duis=consequat&mattis=dui&egestas=nec&metus=nisi&aenean=volutpat&fermentum=eleifend&donec=donec&ut=ut&mauris=dolor&eget=morbi&massa=vel&tempor=lectus&convallis=in&nulla=quam&neque=fringilla&libero=rhoncus&convallis=mauris&eget=enim&eleifend=leo&luctus=rhoncus&ultricies=sed&eu=vestibulum&nibh=sit&quisque=amet&id=cursus&justo=id&sit=turpis&amet=integer&sapien=aliquet&dignissim=massa&vestibulum=id&vestibulum=lobortis&ante=convallis']
['http://washington.edu/erat.xml?vitae=lacinia&consectetuer=eget&eget=tincidunt&rutrum=eget&at=tempus&lorem=vel&integer=pede&tincidunt=morbi&ante=porttitor&vel=lorem&ipsum=id&praesent=ligula&blandit=suspendisse&lacinia=ornare&erat=consequat&vestibulum=lectus&sed=in&magna=est&at=risus&nunc=auctor&commodo=sed&placerat=tristique&praesent=in&blandit=tempus&nam=sit&nulla=amet&integer=sem&pede=fusce&justo=consequat&lacinia=nulla&eget=nisl&tincidunt=nunc&eget=nisl&tempus=duis&vel=bibendum&pede=felis&morbi=sed&porttitor=interdum&lorem=venenatis&id=turpis&ligula=enim&suspendisse=blandit&ornare=mi&consequat=in&lectus=porttitor&in=pede&est=justo&risus=eu&auctor=massa&sed=donec&tristique=dapibus&in=duis&tempus=at&sit=velit&amet=eu&sem=est&fusce=congue&consequat=elementum&nulla=in&nisl=hac&nunc=habitasse&nisl=platea&duis=dictumst&bibendum=morbi&felis=vestibulum&sed=velit&interdum=id&venenatis=pretium&turpis=iaculis&enim=diam&blandit=erat&mi=fermentum&in=justo&porttitor=nec&pede=condimentum&justo=neque&eu=sapien&massa=placerat&donec=ante&dapibus=nulla&duis=justo&at=aliquam']
['https://ning.com/nullam/porttitor/lacus/at/turpis/donec/posuere.js?curabitur=nulla&gravida=justo&nisi=aliquam&at=quis&nibh=turpis&in=eget&hac=elit&habitasse=sodales&platea=scelerisque&dictumst=mauris&aliquam=sit&augue=amet&quam=eros&sollicitudin=suspendisse&vitae=accumsan&consectetuer=tortor&eget=quis&rutrum=turpis&at=sed&lorem=ante&integer=vivamus&tincidunt=tortor&ante=duis&vel=mattis&ipsum=egestas&praesent=metus&blandit=aenean&lacinia=fermentum&erat=donec&vestibulum=ut&sed=mauris&magna=eget&at=massa&nunc=tempor&commodo=convallis&placerat=nulla&praesent=neque&blandit=libero&nam=convallis&nulla=eget&integer=eleifend&pede=luctus&justo=ultricies&lacinia=eu&eget=nibh&tincidunt=quisque&eget=id&tempus=justo&vel=sit&pede=amet&morbi=sapien&porttitor=dignissim&lorem=vestibulum&id=vestibulum&ligula=ante']
['https://kickstarter.com/mattis/egestas.html?nulla=nulla&mollis=elit&molestie=ac&lorem=nulla&quisque=sed&ut=vel&erat=enim&curabitur=sit&gravida=amet&nisi=nunc&at=viverra&nibh=dapibus&in=nulla&hac=suscipit&habitasse=ligula&platea=in&dictumst=lacus&aliquam=curabitur&augue=at&quam=ipsum&sollicitudin=ac&vitae=tellus&consectetuer=semper&eget=interdum&rutrum=mauris&at=ullamcorper&lorem=purus&integer=sit&tincidunt=amet&ante=nulla&vel=quisque&ipsum=arcu&praesent=libero&blandit=rutrum&lacinia=ac']
['http://wikia.com/aliquet/pulvinar/sed/nisl.json?sapien=mi&dignissim=nulla&vestibulum=ac&vestibulum=enim&ante=in&ipsum=tempor&primis=turpis&in=nec&faucibus=euismod&orci=scelerisque&luctus=quam&et=turpis&ultrices=adipiscing&posuere=lorem&cubilia=vitae&curae=mattis&nulla=nibh&dapibus=ligula&dolor=nec&vel=sem&est=duis&donec=aliquam&odio=convallis&justo=nunc&sollicitudin=proin&ut=at&suscipit=turpis&a=a&feugiat=pede&et=posuere&eros=nonummy&vestibulum=integer&ac=non&est=velit&lacinia=donec&nisi=diam&venenatis=neque&tristique=vestibulum&fusce=eget&congue=vulputate&diam=ut&id=ultrices&ornare=vel&imperdiet=augue&sapien=vestibulum&urna=ante&pretium=ipsum&nisl=primis&ut=in&volutpat=faucibus&sapien=orci&arcu=luctus&sed=et&augue=ultrices&aliquam=posuere&erat=cubilia&volutpat=curae&in=donec&congue=pharetra&etiam=magna&justo=vestibulum&etiam=aliquet&pretium=ultrices&iaculis=erat&justo=tortor&in=sollicitudin&hac=mi&habitasse=sit&platea=amet&dictumst=lobortis&etiam=sapien&faucibus=sapien&cursus=non&urna=mi']
['https://ifeng.com/odio/curabitur/convallis/duis/consequat/dui.json?nunc=nunc&vestibulum=rhoncus&ante=dui&ipsum=vel&primis=sem&in=sed&faucibus=sagittis&orci=nam&luctus=congue&et=risus&ultrices=semper&posuere=porta&cubilia=volutpat&curae=quam&mauris=pede&viverra=lobortis&diam=ligula&vitae=sit&quam=amet&suspendisse=eleifend&potenti=pede&nullam=libero&porttitor=quis&lacus=orci&at=nullam&turpis=molestie&donec=nibh&posuere=in&metus=lectus&vitae=pellentesque&ipsum=at&aliquam=nulla&non=suspendisse&mauris=potenti&morbi=cras&non=in&lectus=purus&aliquam=eu&sit=magna&amet=vulputate&diam=luctus&in=cum&magna=sociis&bibendum=natoque&imperdiet=penatibus&nullam=et&orci=magnis&pede=dis&venenatis=parturient&non=montes&sodales=nascetur&sed=ridiculus&tincidunt=mus&eu=vivamus&felis=vestibulum&fusce=sagittis&posuere=sapien&felis=cum&sed=sociis&lacus=natoque&morbi=penatibus&sem=et&mauris=magnis&laoreet=dis&ut=parturient&rhoncus=montes&aliquet=nascetur&pulvinar=ridiculus&sed=mus&nisl=etiam&nunc=vel&rhoncus=augue&dui=vestibulum&vel=rutrum&sem=rutrum&sed=neque&sagittis=aenean&nam=auctor&congue=gravida&risus=sem&semper=praesent&porta=id&volutpat=massa&quam=id&pede=nisl&lobortis=venenatis&ligula=lacinia&sit=aenean&amet=sit', 'https://macromedia.com/sapien/a/libero/nam/dui.aspx?platea=eros&dictumst=suspendisse&aliquam=accumsan&augue=tortor&quam=quis&sollicitudin=turpis&vitae=sed&consectetuer=ante&eget=vivamus&rutrum=tortor&at=duis&lorem=mattis&integer=egestas&tincidunt=metus&ante=aenean&vel=fermentum&ipsum=donec&praesent=ut&blandit=mauris&lacinia=eget&erat=massa&vestibulum=tempor&sed=convallis&magna=nulla&at=neque&nunc=libero&commodo=convallis&placerat=eget&praesent=eleifend&blandit=luctus&nam=ultricies&nulla=eu&integer=nibh&pede=quisque&justo=id&lacinia=justo&eget=sit&tincidunt=amet&eget=sapien&tempus=dignissim&vel=vestibulum&pede=vestibulum&morbi=ante&porttitor=ipsum&lorem=primis&id=in&ligula=faucibus&suspendisse=orci&ornare=luctus&consequat=et&lectus=ultrices&in=posuere&est=cubilia&risus=curae&auctor=nulla&sed=dapibus&tristique=dolor&in=vel&tempus=est&sit=donec&amet=odio&sem=justo&fusce=sollicitudin&consequat=ut&nulla=suscipit&nisl=a&nunc=feugiat&nisl=et&duis=eros&bibendum=vestibulum&felis=ac&sed=est&interdum=lacinia&venenatis=nisi&turpis=venenatis&enim=tristique&blandit=fusce&mi=congue&in=diam&porttitor=id&pede=ornare&justo=imperdiet&eu=sapien&massa=urna&donec=pretium&dapibus=nisl&duis=ut&at=volutpat&velit=sapien&eu=arcu&est=sed&congue=augue&elementum=aliquam&in=erat']
['http://cdc.gov/erat.png?integer=urna&ac=ut&neque=tellus&duis=nulla&bibendum=ut&morbi=erat&non=id&quam=mauris&nec=vulputate&dui=elementum&luctus=nullam&rutrum=varius&nulla=nulla&tellus=facilisi&in=cras&sagittis=non&dui=velit&vel=nec&nisl=nisi&duis=vulputate&ac=nonummy&nibh=maecenas&fusce=tincidunt&lacus=lacus&purus=at&aliquet=velit&at=vivamus&feugiat=vel&non=nulla&pretium=eget&quis=eros&lectus=elementum&suspendisse=pellentesque&potenti=quisque&in=porta&eleifend=volutpat']
['http://instagram.com/turpis/donec.jsp?dui=volutpat&proin=in&leo=congue&odio=etiam&porttitor=justo&id=etiam&consequat=pretium&in=iaculis&consequat=justo&ut=in&nulla=hac&sed=habitasse&accumsan=platea&felis=dictumst&ut=etiam&at=faucibus&dolor=cursus&quis=urna&odio=ut&consequat=tellus&varius=nulla&integer=ut&ac=erat&leo=id&pellentesque=mauris&ultrices=vulputate&mattis=elementum&odio=nullam&donec=varius&vitae=nulla&nisi=facilisi&nam=cras&ultrices=non&libero=velit&non=nec&mattis=nisi&pulvinar=vulputate&nulla=nonummy&pede=maecenas&ullamcorper=tincidunt&augue=lacus&a=at&suscipit=velit&nulla=vivamus&elit=vel&ac=nulla&nulla=eget&sed=eros&vel=elementum&enim=pellentesque&sit=quisque&amet=porta&nunc=volutpat&viverra=erat&dapibus=quisque&nulla=erat&suscipit=eros&ligula=viverra&in=eget&lacus=congue&curabitur=eget&at=semper&ipsum=rutrum&ac=nulla&tellus=nunc&semper=purus&interdum=phasellus&mauris=in&ullamcorper=felis']
['https://theglobeandmail.com/duis/bibendum.xml?metus=molestie&sapien=nibh&ut=in&nunc=lectus&vestibulum=pellentesque&ante=at&ipsum=nulla&primis=suspendisse&in=potenti&faucibus=cras&orci=in&luctus=purus&et=eu&ultrices=magna&posuere=vulputate&cubilia=luctus&curae=cum&mauris=sociis&viverra=natoque&diam=penatibus&vitae=et&quam=magnis&suspendisse=dis&potenti=parturient&nullam=montes&porttitor=nascetur&lacus=ridiculus&at=mus&turpis=vivamus&donec=vestibulum&posuere=sagittis&metus=sapien&vitae=cum&ipsum=sociis&aliquam=natoque&non=penatibus&mauris=et&morbi=magnis&non=dis&lectus=parturient&aliquam=montes&sit=nascetur&amet=ridiculus&diam=mus&in=etiam&magna=vel&bibendum=augue&imperdiet=vestibulum&nullam=rutrum&orci=rutrum&pede=neque&venenatis=aenean&non=auctor&sodales=gravida&sed=sem&tincidunt=praesent&eu=id&felis=massa&fusce=id&posuere=nisl&felis=venenatis&sed=lacinia&lacus=aenean&morbi=sit&sem=amet&mauris=justo&laoreet=morbi&ut=ut&rhoncus=odio&aliquet=cras&pulvinar=mi&sed=pede&nisl=malesuada&nunc=in&rhoncus=imperdiet&dui=et&vel=commodo&sem=vulputate&sed=justo&sagittis=in&nam=blandit']
['http://mapy.cz/accumsan/odio/curabitur/convallis.xml?ultrices=enim&aliquet=in&maecenas=tempor&leo=turpis&odio=nec&condimentum=euismod&id=scelerisque&luctus=quam&nec=turpis&molestie=adipiscing&sed=lorem&justo=vitae&pellentesque=mattis&viverra=nibh&pede=ligula&ac=nec&diam=sem&cras=duis&pellentesque=aliquam&volutpat=convallis&dui=nunc&maecenas=proin&tristique=at&est=turpis&et=a&tempus=pede&semper=posuere&est=nonummy&quam=integer&pharetra=non&magna=velit&ac=donec&consequat=diam&metus=neque&sapien=vestibulum&ut=eget&nunc=vulputate&vestibulum=ut&ante=ultrices&ipsum=vel&primis=augue&in=vestibulum&faucibus=ante&orci=ipsum&luctus=primis&et=in&ultrices=faucibus&posuere=orci&cubilia=luctus&curae=et&mauris=ultrices&viverra=posuere&diam=cubilia&vitae=curae&quam=donec&suspendisse=pharetra&potenti=magna&nullam=vestibulum&porttitor=aliquet&lacus=ultrices&at=erat&turpis=tortor&donec=sollicitudin&posuere=mi&metus=sit&vitae=amet&ipsum=lobortis&aliquam=sapien&non=sapien&mauris=non&morbi=mi&non=integer']
['https://berkeley.edu/non/mi/integer/ac/neque/duis/bibendum.jpg?etiam=elementum&justo=ligula&etiam=vehicula&pretium=consequat&iaculis=morbi&justo=a&in=ipsum&hac=integer&habitasse=a&platea=nibh&dictumst=in&etiam=quis&faucibus=justo&cursus=maecenas&urna=rhoncus&ut=aliquam&tellus=lacus&nulla=morbi&ut=quis&erat=tortor&id=id&mauris=nulla&vulputate=ultrices&elementum=aliquet&nullam=maecenas&varius=leo&nulla=odio&facilisi=condimentum&cras=id&non=luctus&velit=nec&nec=molestie&nisi=sed&vulputate=justo&nonummy=pellentesque&maecenas=viverra&tincidunt=pede&lacus=ac']
['http://seattletimes.com/quis.js?urna=at&ut=velit&tellus=eu&nulla=est&ut=congue&erat=elementum&id=in&mauris=hac&vulputate=habitasse&elementum=platea&nullam=dictumst&varius=morbi&nulla=vestibulum&facilisi=velit&cras=id&non=pretium&velit=iaculis&nec=diam&nisi=erat&vulputate=fermentum&nonummy=justo&maecenas=nec&tincidunt=condimentum']
['https://google.ca/diam/erat/fermentum/justo.js?cubilia=sapien&curae=quis&nulla=libero&dapibus=nullam&dolor=sit&vel=amet&est=turpis&donec=elementum&odio=ligula&justo=vehicula&sollicitudin=consequat&ut=morbi&suscipit=a&a=ipsum&feugiat=integer&et=a&eros=nibh&vestibulum=in&ac=quis&est=justo&lacinia=maecenas&nisi=rhoncus&venenatis=aliquam&tristique=lacus&fusce=morbi&congue=quis&diam=tortor&id=id&ornare=nulla&imperdiet=ultrices&sapien=aliquet&urna=maecenas&pretium=leo&nisl=odio&ut=condimentum&volutpat=id&sapien=luctus&arcu=nec&sed=molestie&augue=sed&aliquam=justo&erat=pellentesque&volutpat=viverra&in=pede&congue=ac&etiam=diam&justo=cras&etiam=pellentesque&pretium=volutpat&iaculis=dui&justo=maecenas&in=tristique&hac=est&habitasse=et&platea=tempus&dictumst=semper&etiam=est&faucibus=quam&cursus=pharetra&urna=magna&ut=ac&tellus=consequat&nulla=metus&ut=sapien&erat=ut&id=nunc&mauris=vestibulum&vulputate=ante&elementum=ipsum&nullam=primis&varius=in&nulla=faucibus&facilisi=orci&cras=luctus&non=et&velit=ultrices&nec=posuere&nisi=cubilia&vulputate=curae&nonummy=mauris&maecenas=viverra&tincidunt=diam&lacus=vitae&at=quam&velit=suspendisse&vivamus=potenti&vel=nullam&nulla=porttitor']
['http://patch.com/eget/nunc/donec.aspx?nunc=tempor&rhoncus=convallis&dui=nulla&vel=neque&sem=libero&sed=convallis&sagittis=eget&nam=eleifend&congue=luctus&risus=ultricies&semper=eu&porta=nibh&volutpat=quisque&quam=id']
['http://un.org/id/luctus/nec.png?nisi=dui&eu=vel&orci=nisl&mauris=duis&lacinia=ac']
['http://kickstarter.com/sapien.png?ultrices=nec&enim=condimentum&lorem=neque&ipsum=sapien&dolor=placerat&sit=ante&amet=nulla&consectetuer=justo&adipiscing=aliquam']
['https://digg.com/velit/eu/est/congue.xml?proin=sit&at=amet&turpis=consectetuer&a=adipiscing&pede=elit&posuere=proin&nonummy=risus&integer=praesent&non=lectus&velit=vestibulum&donec=quam&diam=sapien&neque=varius&vestibulum=ut&eget=blandit&vulputate=non&ut=interdum&ultrices=in&vel=ante&augue=vestibulum&vestibulum=ante&ante=ipsum&ipsum=primis&primis=in&in=faucibus&faucibus=orci&orci=luctus&luctus=et&et=ultrices&ultrices=posuere&posuere=cubilia&cubilia=curae&curae=duis&donec=faucibus&pharetra=accumsan&magna=odio&vestibulum=curabitur&aliquet=convallis&ultrices=duis&erat=consequat&tortor=dui&sollicitudin=nec&mi=nisi&sit=volutpat&amet=eleifend&lobortis=donec&sapien=ut&sapien=dolor&non=morbi&mi=vel&integer=lectus&ac=in&neque=quam&duis=fringilla&bibendum=rhoncus&morbi=mauris&non=enim&quam=leo&nec=rhoncus&dui=sed&luctus=vestibulum&rutrum=sit&nulla=amet&tellus=cursus&in=id&sagittis=turpis&dui=integer&vel=aliquet&nisl=massa&duis=id&ac=lobortis&nibh=convallis&fusce=tortor&lacus=risus&purus=dapibus&aliquet=augue&at=vel&feugiat=accumsan&non=tellus&pretium=nisi&quis=eu&lectus=orci&suspendisse=mauris&potenti=lacinia&in=sapien&eleifend=quis&quam=libero&a=nullam&odio=sit']
['https://nationalgeographic.com/ut/at/dolor/quis.js?diam=in&id=hac&ornare=habitasse&imperdiet=platea&sapien=dictumst&urna=aliquam&pretium=augue&nisl=quam&ut=sollicitudin&volutpat=vitae&sapien=consectetuer&arcu=eget&sed=rutrum&augue=at&aliquam=lorem&erat=integer&volutpat=tincidunt&in=ante&congue=vel&etiam=ipsum&justo=praesent&etiam=blandit&pretium=lacinia&iaculis=erat&justo=vestibulum&in=sed&hac=magna&habitasse=at&platea=nunc&dictumst=commodo&etiam=placerat&faucibus=praesent&cursus=blandit&urna=nam&ut=nulla&tellus=integer&nulla=pede&ut=justo&erat=lacinia']
['http://theguardian.com/nisi/venenatis/tristique/fusce/congue/diam/id.js?duis=amet&mattis=consectetuer&egestas=adipiscing&metus=elit&aenean=proin&fermentum=interdum&donec=mauris']
['https://topsy.com/duis/faucibus/accumsan/odio/curabitur/convallis/duis.jsp?nulla=posuere&tellus=cubilia&in=curae&sagittis=mauris&dui=viverra&vel=diam&nisl=vitae&duis=quam&ac=suspendisse&nibh=potenti&fusce=nullam&lacus=porttitor&purus=lacus&aliquet=at&at=turpis&feugiat=donec&non=posuere&pretium=metus&quis=vitae&lectus=ipsum&suspendisse=aliquam&potenti=non&in=mauris&eleifend=morbi&quam=non&a=lectus&odio=aliquam&in=sit&hac=amet&habitasse=diam&platea=in&dictumst=magna&maecenas=bibendum&ut=imperdiet&massa=nullam&quis=orci&augue=pede&luctus=venenatis&tincidunt=non&nulla=sodales&mollis=sed&molestie=tincidunt&lorem=eu&quisque=felis']
['https://oakley.com/lobortis.aspx?sed=feugiat&tincidunt=et&eu=eros&felis=vestibulum&fusce=ac&posuere=est&felis=lacinia&sed=nisi&lacus=venenatis&morbi=tristique&sem=fusce&mauris=congue&laoreet=diam&ut=id&rhoncus=ornare&aliquet=imperdiet&pulvinar=sapien&sed=urna&nisl=pretium&nunc=nisl&rhoncus=ut&dui=volutpat&vel=sapien&sem=arcu&sed=sed&sagittis=augue&nam=aliquam&congue=erat&risus=volutpat&semper=in&porta=congue&volutpat=etiam&quam=justo&pede=etiam&lobortis=pretium&ligula=iaculis&sit=justo&amet=in&eleifend=hac&pede=habitasse&libero=platea&quis=dictumst&orci=etiam&nullam=faucibus&molestie=cursus&nibh=urna&in=ut&lectus=tellus&pellentesque=nulla&at=ut']
['http://ebay.co.uk/convallis/nunc/proin.xml?vel=eu&sem=orci&sed=mauris&sagittis=lacinia&nam=sapien&congue=quis&risus=libero&semper=nullam&porta=sit&volutpat=amet&quam=turpis&pede=elementum&lobortis=ligula&ligula=vehicula&sit=consequat&amet=morbi&eleifend=a&pede=ipsum&libero=integer&quis=a&orci=nibh&nullam=in&molestie=quis&nibh=justo&in=maecenas&lectus=rhoncus&pellentesque=aliquam&at=lacus&nulla=morbi&suspendisse=quis&potenti=tortor&cras=id&in=nulla&purus=ultrices&eu=aliquet&magna=maecenas&vulputate=leo&luctus=odio&cum=condimentum&sociis=id&natoque=luctus&penatibus=nec&et=molestie&magnis=sed&dis=justo&parturient=pellentesque&montes=viverra&nascetur=pede&ridiculus=ac&mus=diam&vivamus=cras&vestibulum=pellentesque&sagittis=volutpat&sapien=dui&cum=maecenas&sociis=tristique&natoque=est&penatibus=et&et=tempus&magnis=semper&dis=est&parturient=quam&montes=pharetra&nascetur=magna']

In [ ]:

# %pip install requests

In [73]:
import requests