In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv(r"C:\Users\chava\Downloads\student_performance.csv")
print(df)
df.sample(10)

        student_id  weekly_self_study_hours  attendance_percentage  \
0                1                     18.5                   95.6
1                2                     14.0                   80.0
2                3                     19.5                   86.3
3                4                     25.7                   70.2
4                5                     13.4                   81.9
...            ...                      ...                    ...
999995      999996                     18.0                   95.5
999996      999997                     15.7                   82.7
999997      999998                     14.2                   85.1
999998      999999                     25.3                   90.0
999999     1000000                     18.3                   84.6

        class_participation  total_score grade
0                       3.8         97.9     A
1                       2.5         83.9     B
2                       5.3        100.0     A
3                       7.0        100.0     A
4                       6.9         92.0     A
...                     ...          ...   ...
999995                  4.8        100.0     A
999996                  6.7         88.3     A
999997                  5.8         87.9     A
999998                  5.3        100.0     A
999999                  4.1        100.0     A

[1000000 rows x 6 columns]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
630834,630835,7.4,94.0,6.9,58.4,C
335926,335927,23.7,99.1,8.9,93.5,A
205378,205379,19.5,75.0,5.8,100.0,A
667746,667747,7.9,83.1,9.8,69.7,C
782736,782737,15.5,91.0,5.9,80.3,B
684623,684624,17.7,69.3,4.2,86.8,A
785127,785128,13.6,69.7,7.8,100.0,A
12737,12738,10.6,74.7,5.6,79.6,B
871823,871824,29.8,77.3,6.7,100.0,A
731191,731192,15.9,75.6,3.7,100.0,A

In [16]:
df=df.rename(columns={"weekly_self_study_hours":"study_hours"})

In [17]:
df=df[["student_id","attendance_percentage","class_participation","study_hours","total_score","grade"]]

In [18]:
df.groupby("grade")["study_hours"].mean()
df.groupby("grade")["student_id"].count()
df.groupby("total_score")["attendance_percentage"].max()
df.groupby("grade")["attendance_percentage"].min()
df.groupby("grade")["study_hours"].std()

grade
A    5.146787
B    3.712152
C    3.746585
D    3.155624
F    2.060110
Name: study_hours, dtype: float64

In [19]:
df.groupby("total_score")["study_hours"].agg(["min","max","mean","count"])

             min   max       mean   count
total_score
9.4          0.0   0.0   0.000000       1
12.2         0.0   0.0   0.000000       1
14.4         0.0   0.0   0.000000       1
14.6         0.0   1.5   0.750000       2
14.7         0.8   0.8   0.800000       1
...          ...   ...        ...     ...
99.6         8.6  30.9  18.432861    1692
99.7         7.2  30.0  18.671603    1641
99.8         5.5  30.5  18.619795    1657
99.9         6.4  29.7  18.765627    1571
100.0        4.6  40.0  22.458261  268121

[824 rows x 4 columns]

In [23]:
df.groupby("grade")["total_score"].agg(min_marks="min",max_marks="max")#only two columns allowed

       min_marks  max_marks
grade
A           85.0      100.0
B           70.0       85.0
C           55.0       70.0
D           40.0       55.0
F            9.4       40.0

In [32]:
df.groupby("grade").agg({"study_hours":"mean","total_score":"mean"})

       study_hours  total_score
grade
A        19.375738    96.042375
B        12.115533    77.946590
C         7.691161    63.564524
D         3.764143    49.380346
F         1.524662    35.474146

In [33]:
df.groupby("grade").agg(avg_hours_of_study=("study_hours","mean"),avg_total_score=("total_score","mean"))

       avg_hours_of_study  avg_total_score
grade
A               19.375738        96.042375
B               12.115533        77.946590
C                7.691161        63.564524
D                3.764143        49.380346
F                1.524662        35.474146